### ISSUE TITLE
installjob_skylake.sh broken

### ISSUE THREAD

**Issue by camarocico** [rug-cit-hpc/cit-hpc-easybuild#8] opened 2022-03-30 07:31 UTC
When submitting a job to skylake nodes, I get this error:

`sbatch: error: Batch job submission failed: Requested node configuration is not available`

Probably something to do with removing the vulture nodes, I'm guessing that

`#SBATCH constraint=12cores`

needs to be removed.

**Comment by FokkeDijkstra** [comment] 2022-03-30 08:02
It is indeed caused by the removal of the vulture nodes from RUGcloud, which were skylake based. 
The constraint tried to make sure that these were selected.
I think the only way to fix this is to use the V100 GPU nodes instead. I will check if any other nodes have skylake based CPUs.

**Comment by FokkeDijkstra** [comment] 2022-03-30 08:05
All other vulture nodes are from an older architecture. So we need to use V100 based GPU nodes for Skylake.

**Comment by FokkeDijkstra** [comment] 2022-03-30 08:11
Addressed in #9

**Closed as completed** 2022-03-30 09:10 UTC
Labels: bug
